---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Update repository and Upgrade packages
    apt:
      upgrade: dist
      update_cache: yes
  - name: Install Nginx
    apt:
      name:
        - nginx
        - nmap
      state: latest
